.PHONY: clean All

All:
	@echo "==========Building project:[ Lesson1 - Debug ]=========="
	@"$(MAKE)" -f  "Lesson1.mk"
clean:
	@echo "==========Cleaning project:[ Lesson1 - Debug ]----------"
	@"$(MAKE)" -f  "Lesson1.mk" clean
